allowBuilds:
  '@google/genai': false
  '@swc/core': true
  esbuild: false
  protobufjs: false

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.23
  vite-plus: ^0.1.23
  vitest: npm:@voidzero-dev/vite-plus-test@~0.1.23

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@enonic/ui'
  - '@enonic-types/*'
  - '@typescript/native-preview*'

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
